### PR TITLE
Add CSS Color variables

### PR DESCRIPTION
**Pull request by Yinkajay**
This PR...

## Changes
The main.css file by adding the CSS color variable names from the Figma document

### CODE REVIEW

**Comment by Boye95** [comment]
Thanks, @Yinkajay. I believe you meant it changed the index.css file.

@all-contributors please add @Yinkajay  as a contributor

**Review by Boye95 — APPROVED** [review]
Thanks for your contribution @Yinkajay

**Comment by Yinkajay** [comment]
Yes, the index.css file.
You are welcome

**Comment by Boye95** [comment]
> Yes, the index.css file. You are welcome

100%

**Comment by Boye95** [comment]
@all-contributors please add @Yinkajay for code

**Pull request merged**
