### PR TITLE
update: integrated the login path to altstudent component

### PR DESCRIPTION
**Pull request by vader-js**
This PR...

## Changes

-

## Fixes
-

## Checklist

- [x] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [x] added/updated a component
- [x] fixed a bug
- [x] added/updated a new route
- [x] added or changed css styles

Fixes #

### CODE REVIEW

**Review by Boye95 — CHANGES_REQUESTED** [review]
Thanks Ayo. PR title should be more explanatory and the template should be followed

**Review by Watermelon-Sugar — DISMISSED** [review]
Approved

**Comment by vader-js** [comment]
what template

**Comment by vader-js** [comment]
> Thanks Ayo. PR title should be more explanatory and the template should be followed

what template

**Comment by Boye95** [comment]
> > Thanks Ayo. PR title should be more explanatory and the template should be followed
> 
> what template

The PR template with the checkboxes

**Review by Boye95 — APPROVED** [review]
Thanks @vader-js

**Pull request merged**
